name: saturnotpv
description: "Punto de venta y sistema de gestión para Saturno."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cloud_firestore: ^4.17.5
  firebase_core: ^2.32.0
  cupertino_icons: ^1.0.6
  intl: ^0.20.2 # Versión actualizada para resolver el conflicto
  share_plus: ^10.0.0
  google_fonts: ^8.0.0
  flutter_svg: ^2.0.7
  firebase_auth: ^4.16.0
  fl_chart: ^0.68.0
  go_router: ^17.0.1
  pinput: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: LemonMilk
      fonts:
        - asset: assets/LEMONMILK-Light.otf
          weight: 300
        - asset: assets/LEMONMILK-Medium.otf
          weight: 500
        - asset: assets/LEMONMILK-Bold.otf
          weight: 700
